"""Bundle the place's ModuleScripts into one Lune-runnable Luau file.

Each module becomes  __loaders["Full.Name"] = function(script) <source> end  so it keeps
Roblox's safe environment (builtins fastcall) instead of running under a custom fenv.
`require(instance)` resolves through instance:GetFullName().

usage: bundle.py <src_dir> <out.luau> [root ...]
"""
import os
import re
import sys

src_dir, out_path = sys.argv[1], sys.argv[2]
roots = sys.argv[3:] or ["ReplicatedStorage", "ServerScriptService", "ReplicatedFirst", "StarterPlayer"]

man = os.path.join(src_dir, "_manifest.tsv")
if not os.path.exists(man):
    man = os.path.join(os.path.dirname(os.path.abspath(src_dir)), "manifest.tsv")
rows = [l.split("\t") for l in open(man).read().splitlines()]
EXPORT_RE = re.compile(r"^(\s*)export\s+type\b", re.M)

# Modules added since the manifest was written (new files in the tree).
known = {r[3] for r in rows}
for dp, dn, fn in os.walk(src_dir):
    for f in fn:
        if not f.endswith(".luau") or f.endswith(".client.luau") or f.endswith(".server.luau"):
            continue
        rel = os.path.relpath(os.path.join(dp, f), src_dir)
        if rel in known:
            continue
        rows.append(["0", "ModuleScript", rel[:-5].replace(os.sep, "."), rel])
parts = []
seen = set()
for ref, cls, full, rel in rows:
    if cls != "ModuleScript":
        continue
    if not any(full.startswith(r + ".") for r in roots):
        continue
    if full in seen:
        continue
    seen.add(full)
    src = open(os.path.join(src_dir, rel), encoding="utf-8", errors="replace").read()
    src = EXPORT_RE.sub(r"\1type", src)
    # Harness-only: Lune mis-resolves `.Terrain` on any instance (it hits Workspace.Terrain).
    def _outside(pat, rep, text):
        out = []
        for line in text.split("\n"):
            def sub(m):
                before = line[:m.start()]
                if before.count('"') % 2 or before.count("'") % 2 or "--" in before:
                    return m.group(0)
                return m.expand(rep)
            out.append(re.sub(pat, sub, line))
        return "\n".join(out)
    src = _outside(r"\b(ReplicatedStorage|Services|RS)\.Terrain\b", r'\1:FindFirstChild("Terrain")', src)
    src = _outside(r"\b([Ww]orkspace)\.Terrain\b", r'\1:FindFirstChildOfClass("Terrain")', src)
    # A module body must end with its return; a stray trailing return-less file still works.
    if full.endswith(".spec"):
        src = "local describe, it, expect = shared.describe, shared.it, shared.expect\n" + src
    parts.append("__loaders[%s] = function(script)\n%s\nend\n" % (repr(full).replace("'", '"') if '"' not in full else repr(full), src))

with open(out_path, "w", encoding="utf-8") as f:
    f.write("-- generated by tools/bundle.py\n")
    f.write("return function(__loaders, require, game, workspace, Enum, Instance, Vector3, Vector2, CFrame, Color3, Region3, BrickColor, UDim2, UDim, NumberSequence, NumberSequenceKeypoint, ColorSequence, ColorSequenceKeypoint, NumberRange, Ray, Random, task, warn, tick, Content, Font, PhysicalProperties, RaycastParams, OverlapParams, TweenInfo, DateTime, Rect, Faces, Axes, Vector3int16, Region3int16, shared, delay, spawn, wait)\n")
    for p in parts:
        f.write(p)
    f.write("end\n")
print("bundled", len(parts), "modules ->", out_path)
